"""Agregar campos para ChatGPT y reorganizar modelo

Revision ID: 3cdfaddcca7f
Revises: 
Create Date: 2024-07-24 00:27:10.590651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdfaddcca7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificacion_pais_residencia_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_edad_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_estado_civil_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_hijos_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_vivienda_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_profesion_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_nivel_educacion_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_tiempo_empleo_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_propietario_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_ingresos_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_impuestos_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_propiedades_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_viajes_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_familiares_eeuu_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_familiares_visa_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_visa_negada_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_antecedentes_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_enfermedades_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_visa_otra_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_problemas_migratorios_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_nacionalidad_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_criterios_confidenciales_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sugerencia_1_ChatGPT', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sugerencia_2_ChatGPT', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sugerencia_3_ChatGPT', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_categoria_informacion_demografica_familiar_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_categoria_educacion_empleo_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_categoria_propiedades_activos_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_categoria_antecedentes_experiencia_viaje_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_categoria_criterios_confidenciales_ChatGPT', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_result', schema=None) as batch_op:
        batch_op.drop_column('notas')
        batch_op.drop_column('calificacion_categoria_criterios_confidenciales_ChatGPT')
        batch_op.drop_column('calificacion_categoria_antecedentes_experiencia_viaje_ChatGPT')
        batch_op.drop_column('calificacion_categoria_propiedades_activos_ChatGPT')
        batch_op.drop_column('calificacion_categoria_educacion_empleo_ChatGPT')
        batch_op.drop_column('calificacion_categoria_informacion_demografica_familiar_ChatGPT')
        batch_op.drop_column('sugerencia_3_ChatGPT')
        batch_op.drop_column('sugerencia_2_ChatGPT')
        batch_op.drop_column('sugerencia_1_ChatGPT')
        batch_op.drop_column('calificacion_criterios_confidenciales_ChatGPT')
        batch_op.drop_column('calificacion_nacionalidad_ChatGPT')
        batch_op.drop_column('calificacion_problemas_migratorios_ChatGPT')
        batch_op.drop_column('calificacion_visa_otra_ChatGPT')
        batch_op.drop_column('calificacion_enfermedades_ChatGPT')
        batch_op.drop_column('calificacion_antecedentes_ChatGPT')
        batch_op.drop_column('calificacion_visa_negada_ChatGPT')
        batch_op.drop_column('calificacion_familiares_visa_ChatGPT')
        batch_op.drop_column('calificacion_familiares_eeuu_ChatGPT')
        batch_op.drop_column('calificacion_viajes_ChatGPT')
        batch_op.drop_column('calificacion_propiedades_ChatGPT')
        batch_op.drop_column('calificacion_impuestos_ChatGPT')
        batch_op.drop_column('calificacion_ingresos_ChatGPT')
        batch_op.drop_column('calificacion_propietario_ChatGPT')
        batch_op.drop_column('calificacion_tiempo_empleo_ChatGPT')
        batch_op.drop_column('calificacion_nivel_educacion_ChatGPT')
        batch_op.drop_column('calificacion_profesion_ChatGPT')
        batch_op.drop_column('calificacion_vivienda_ChatGPT')
        batch_op.drop_column('calificacion_hijos_ChatGPT')
        batch_op.drop_column('calificacion_estado_civil_ChatGPT')
        batch_op.drop_column('calificacion_edad_ChatGPT')
        batch_op.drop_column('calificacion_pais_residencia_ChatGPT')

    # ### end Alembic commands ###
