"""empty message

Revision ID: e73b300cfa02
Revises: ee39fc5f7785
Create Date: 2024-10-04 11:33:06.259902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73b300cfa02'
down_revision = 'ee39fc5f7785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('roles')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), server_default=sa.text("'default_password'"), nullable=False))
        batch_op.add_column(sa.Column('roles', sa.INTEGER(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
