"""Actualizar columnas a Text para almacenar datos de ChatGPT

Revision ID: ff43aaba5950
Revises: 3cdfaddcca7f
Create Date: 2024-07-24 10:38:21.454471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff43aaba5950'
down_revision = '3cdfaddcca7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_result', schema=None) as batch_op:
        batch_op.alter_column('calificacion_pais_residencia_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_edad_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_estado_civil_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_hijos_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_vivienda_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_profesion_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_nivel_educacion_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_tiempo_empleo_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_propietario_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_ingresos_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_impuestos_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_propiedades_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_viajes_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_familiares_eeuu_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_familiares_visa_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_visa_negada_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_antecedentes_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_enfermedades_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_visa_otra_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_problemas_migratorios_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_nacionalidad_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_criterios_confidenciales_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_informacion_demografica_familiar_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_educacion_empleo_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_propiedades_activos_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_antecedentes_experiencia_viaje_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_criterios_confidenciales_ChatGPT',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_result', schema=None) as batch_op:
        batch_op.alter_column('calificacion_categoria_criterios_confidenciales_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_antecedentes_experiencia_viaje_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_propiedades_activos_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_educacion_empleo_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_categoria_informacion_demografica_familiar_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_criterios_confidenciales_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_nacionalidad_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_problemas_migratorios_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_visa_otra_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_enfermedades_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_antecedentes_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_visa_negada_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_familiares_visa_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_familiares_eeuu_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_viajes_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_propiedades_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_impuestos_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_ingresos_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_propietario_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_tiempo_empleo_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_nivel_educacion_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_profesion_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_vivienda_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_hijos_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_estado_civil_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_edad_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('calificacion_pais_residencia_ChatGPT',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
